repos:
  - repo: local
    hooks:
      - id: schema-validator
        name: Schema Validator
        entry: python validate_codex.py
        language: python
        types: [yaml]
        always_run: true
        pass_filenames: false
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: \.(yml|yaml)$
