name: Validate Codex Schema

on:
  pull_request:
    paths: ["config.yaml", "schema/codex_validator_schema.json"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install pyyaml jsonschema
      - name: Validate schema
        run: |
          python -c "
          import yaml
          import json
          import jsonschema
          with open('config.yaml') as y: data = yaml.safe_load(y)
          with open('schema/codex_validator_schema.json') as s:
            schema = json.load(s)
          jsonschema.validate(instance=data, schema=schema)
          "
